-- Creates the "MANM" schema and all tables with data
-- Column names (e.g., item_code) are in snake_case to match your API routes

-- 1. Create the schema
CREATE SCHEMA IF NOT EXISTS "MANM";

-- 2. Drop tables in correct order (or just drop schema cascade)
DROP TABLE IF EXISTS "MANM".mrp;
DROP TABLE IF EXISTS "MANM".procurement;
DROP TABLE IF EXISTS "MANM".inventory;
DROP TABLE IF EXISTS "MANM".mps;
DROP TABLE IF EXISTS "MANM".customer_orders;
DROP TABLE IF EXISTS "MANM".quality_control;
DROP TABLE IF EXISTS "MANM".logistics;

-- -----------------------------------------------------
-- Table "MANM".customer_orders
-- 'id' is SERIAL PRIMARY KEY as used by your PUT/DELETE routes
-- 'order_number' is a separate column as generated by your POST route
-- -----------------------------------------------------
CREATE TABLE "MANM".customer_orders (
  "id" SERIAL PRIMARY KEY,
  "order_number" VARCHAR(20) NOT NULL UNIQUE,
  "customer_name" VARCHAR(100) NOT NULL,
  "product_name" VARCHAR(100) NOT NULL,
  "order_date" DATE NOT NULL,
  "delivery_date" DATE NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "total_value" DECIMAL(12, 2) NOT NULL,
  "items" INT NOT NULL
);

-- -----------------------------------------------------
-- Table "MANM".inventory
-- -----------------------------------------------------
CREATE TABLE "MANM".inventory (
  "item_code" VARCHAR(20) NOT NULL PRIMARY KEY,
  "item_name" VARCHAR(100) NOT NULL,
  "category" VARCHAR(50) NULL,
  "current_stock" INT NOT NULL DEFAULT 0,
  "minimum_stock" INT NOT NULL DEFAULT 0,
  "maximum_stock" INT NOT NULL DEFAULT 1000,
  "location" VARCHAR(50) NULL,
  "unit_price" DECIMAL(10, 2) NOT NULL,
  "status" VARCHAR(20) NOT NULL,
  "last_updated" DATE NULL
);

-- -----------------------------------------------------
-- Table "MANM".mrp
-- NO 'available_qty' or 'shortfall' columns, as your API calculates them live
-- -----------------------------------------------------
CREATE TABLE "MANM".mrp (
  "material_code" VARCHAR(20) NOT NULL PRIMARY KEY,
  "material_name" VARCHAR(100) NOT NULL,
  "item_code" VARCHAR(20) NOT NULL, -- The item_code from inventory
  "related_order" VARCHAR(20) NULL,
  "required_qty" INT NOT NULL,
  "supplier" VARCHAR(100) NULL,
  "lead_time" VARCHAR(20) NULL,
  "status" VARCHAR(20) NOT NULL,
  "planned_date" DATE NULL
  -- FOREIGN KEY ("item_code") REFERENCES "MANM".inventory("item_code"),
  -- FOREIGN KEY ("related_order") REFERENCES "MANM".customer_orders("order_number")
);


-- -----------------------------------------------------
-- Table "MANM".mps
-- Columns match your mps.js file (omits progress, actual dates)
-- -----------------------------------------------------
CREATE TABLE "MANM".mps (
  "schedule_id" VARCHAR(20) NOT NULL PRIMARY KEY,
  "product_name" VARCHAR(100) NOT NULL,
  "order_number" VARCHAR(20) NOT NULL,
  "planned_start_date" DATE NULL,
  "planned_end_date" DATE NULL,
  "status" VARCHAR(20) NOT NULL,
  "priority" VARCHAR(20) NULL,
  "workstation" VARCHAR(50) NULL,
  "supervisor" VARCHAR(100) NULL
  -- FOREIGN KEY ("order_number") REFERENCES "MANM".customer_orders("order_number")
);

-- -----------------------------------------------------
-- Table "MANM".quality_control
-- -----------------------------------------------------
CREATE TABLE "MANM".quality_control (
  "inspection_id" VARCHAR(20) NOT NULL PRIMARY KEY,
  "product_name" VARCHAR(100) NOT NULL,
  "batch_number" VARCHAR(20) NULL,
  "inspection_date" DATE NULL,
  "inspector" VARCHAR(100) NULL,
  "test_type" VARCHAR(50) NULL,
  "result" VARCHAR(20) NULL,
  "defect_count" INT NOT NULL DEFAULT 0,
  "notes" VARCHAR(255) NULL
);

-- -----------------------------------------------------
-- Table "MANM".logistics
-- -----------------------------------------------------
CREATE TABLE "MANM".logistics (
  "shipment_id" VARCHAR(20) NOT NULL PRIMARY KEY,
  "order_number" VARCHAR(20) NOT NULL,
  "carrier" VARCHAR(50) NULL,
  "tracking_number" VARCHAR(50) NULL,
  "origin" VARCHAR(50) NULL,
  "destination" VARCHAR(50) NULL,
  "departure_date" DATE NULL,
  "estimated_arrival" DATE NULL,
  "status" VARCHAR(20) NULL,
  "priority" VARCHAR(20) NULL
);

-- -----------------------------------------------------
-- Table "MANM".procurement
-- -----------------------------------------------------
CREATE TABLE "MANM".procurement (
  "po_number" VARCHAR(20) NOT NULL PRIMARY KEY,
  "supplier" VARCHAR(100) NOT NULL,
  "material_name" VARCHAR(100) NULL,
  "item_code" VARCHAR(20) NULL,
  "quantity" INT NOT NULL,
  "unit_price" DECIMAL(10, 2) NULL,
  "total_amount" DECIMAL(10, 2) NULL,
  "order_date" DATE NULL,
  "expected_delivery" DATE NULL,
  "status" VARCHAR(20) NULL,
  "related_order" VARCHAR(20) NULL
);

ALTER TABLE "MANM".procurement
ALTER COLUMN unit_price TYPE DECIMAL(10, 2);

-- -----------------------------------------------------
-- INSERT DATA
-- -----------------------------------------------------

-- Populate "MANM".inventory
INSERT INTO "MANM".inventory ("item_code", "item_name", "category", "current_stock", "minimum_stock", "maximum_stock", "location", "unit_price", "status", "last_updated") VALUES
('INV-0001', 'Aluminum Rods 6mm', 'Raw Materials', 450, 200, 1000, 'Warehouse A-1', 12.50, 'In Stock', '2025-01-28'),
('INV-0002', 'Steel Bolts M8x50', 'Fasteners', 85, 100, 500, 'Warehouse B-2', 0.75, 'Low Stock', '2025-01-27'),
('INV-0003', 'Rubber Gaskets', 'Sealing', 0, 50, 300, 'Warehouse C-1', 3.25, 'Out of Stock', '2025-01-26'),
('INV-0004', 'Electric Motors 5HP', 'Components', 15, 10, 50, 'Warehouse D-3', 450.00, 'In Stock', '2025-01-25'),
('INV-0005', 'Circuit Boards PCB-A1', 'Electronics', 75, 25, 200, 'Warehouse E-1', 85.00, 'In Stock', '2025-01-24'),
('INV-0015', 'Titanium Screws', 'Fasteners', 0, 150, 600, 'Warehouse B-3', 2.50, 'Out of Stock', '2025-01-14');

-- Populate "MANM".customer_orders (Note: 'id' is not in INSERT list, it's auto-generated)
INSERT INTO "MANM".customer_orders ("order_number", "customer_name", "product_name", "order_date", "delivery_date", "status", "total_value", "items") VALUES
('CO-2025-001', 'Luxury Home Interiors', 'Glass Dining Table', '2025-01-15', '2025-02-15', 'Processing', 85000.00, 1),
('CO-2025-002', 'Corporate Office Solutions', 'Steel Office Desk', '2025-01-18', '2025-02-18', 'Processing', 45500.00, 2),
('CO-2025-003', 'Metro Construction Ltd', 'Aluminum Window Frame', '2025-01-20', '2025-02-20', 'Processing', 32750.00, 10),
('CO-2025-004', 'Precision Manufacturing', 'Motor Assembly Unit', '2025-01-22', '2025-02-22', 'Processing', 125000.00, 5),
('CO-2025-005', 'Tech Solutions Inc', 'Circuit Board Assembly', '2025-01-25', '2025-02-25', 'Processing', 78500.00, 8),
('CO-2025-006', 'Automotive Parts Ltd', 'Hydraulic System', '2025-01-27', '2025-02-27', 'Processing', 95000.00, 3),
('CO-2025-007', 'Energy Systems Corp', 'Solar Panel Frame', '2025-01-29', '2025-03-01', 'Processing', 52000.00, 20);

-- Populate "MANM".mrp (item_code is manually mapped, available/shortfall are omitted)
INSERT INTO "MANM".mrp ("material_code", "material_name", "item_code", "related_order", "required_qty", "supplier", "lead_time", "status", "planned_date") VALUES
('MAT-001-A', 'Aluminum Rods 6mm', 'INV-0001', 'CO-2025-001', 10, 'Aluminum Solutions Inc', '3 days', 'Available', '2025-01-20'),
('MAT-001-B', 'Steel Bolts M8x50', 'INV-0002', 'CO-2025-001', 20, 'MetalCraft Industries', '2 days', 'Available', '2025-01-20'),
('MAT-002-A', 'Aluminum Rods 6mm', 'INV-0001', 'CO-2025-002', 15, 'Aluminum Solutions Inc', '3 days', 'Available', '2025-01-22'),
('MAT-002-B', 'Steel Bolts M8x50', 'INV-0002', 'CO-2025-002', 30, 'MetalCraft Industries', '2 days', 'Available', '2025-01-22'),
('MAT-003-A', 'Aluminum Rods 6mm', 'INV-0001', 'CO-2025-003', 25, 'Aluminum Solutions Inc', '3 days', 'Available', '2025-01-24'),
('MAT-003-B', 'Rubber Gaskets', 'INV-0003', 'CO-2025-003', 10, 'Rubber Industries', '5 days', 'Required', '2025-01-24'),
('MAT-004-A', 'Electric Motors 5HP', 'INV-0004', 'CO-2025-004', 1, 'Precision Motors Ltd', '7 days', 'Available', '2025-01-26'),
('MAT-004-B', 'Circuit Boards PCB-A1', 'INV-0005', 'CO-2025-004', 2, 'Electronics Supply Co', '4 days', 'Available', '2025-01-26'),
('MAT-005-A', 'Circuit Boards PCB-A1', 'INV-0005', 'CO-2025-005', 5, 'Electronics Supply Co', '4 days', 'Available', '2025-01-28'),
('MAT-006-A', 'Steel Bolts M8x50', 'INV-0002', 'CO-2025-006', 40, 'MetalCraft Industries', '2 days', 'Shortage', '2025-01-30'),
('MAT-006-B', 'Electric Motors 5HP', 'INV-0004', 'CO-2025-006', 2, 'Precision Motors Ltd', '7 days', 'Available', '2025-01-30'),
('MAT-007-A', 'Aluminum Rods 6mm', 'INV-0001', 'CO-2025-007', 30, 'Aluminum Solutions Inc', '3 days', 'Available', '2025-02-01'),
('MAT-007-B', 'Titanium Screws', 'INV-0015', 'CO-2025-007', 20, 'Titanium Tech Ltd', '10 days', 'Required', '2025-02-01');

-- Populate "MANM".mps (omitting progress, actual dates)
INSERT INTO "MANM".mps ("schedule_id", "product_name", "order_number", "planned_start_date", "planned_end_date", "status", "priority", "workstation", "supervisor") VALUES
('PS-2025-001', 'Glass Dining Table', 'CO-2025-001', '2025-02-01', '2025-02-15', 'In Progress', 'High', 'Assembly Line A', 'John Smith'),
('PS-2025-002', 'Steel Office Desk', 'CO-2025-002', '2025-02-03', '2025-02-18', 'In Progress', 'Medium', 'Fabrication Bay B', 'Sarah Johnson'),
('PS-2025-003', 'Aluminum Window Frame', 'CO-2025-003', '2025-02-05', '2025-02-20', 'On Hold', 'Medium', 'Extrusion Line C', 'Mike Wilson'),
('PS-2025-004', 'Motor Assembly Unit', 'CO-2025-004', '2025-02-07', '2025-02-22', 'Scheduled', 'High', 'Motor Assembly D', 'Emily Davis'),
('PS-2025-005', 'Circuit Board Assembly', 'CO-2025-005', '2025-02-10', '2025-02-25', 'In Progress', 'High', 'Electronics Lab E', 'Robert Brown'),
('PS-2025-006', 'Hydraulic System', 'CO-2025-006', '2025-02-12', '2025-02-27', 'On Hold', 'Medium', 'Hydraulics Bay F', 'Lisa Chen'),
('PS-2025-007', 'Solar Panel Frame', 'CO-2025-007', '2025-02-14', '2025-03-01', 'On Hold', 'Low', 'Frame Assembly G', 'Tom Anderson');

-- Populate "MANM".quality_control
INSERT INTO "MANM".quality_control ("inspection_id", "product_name", "batch_number", "inspection_date", "inspector", "test_type", "result", "defect_count", "notes") VALUES
('QC-2025-001', 'Glass Dining Table', 'GDT-001', '2025-01-15', 'John Smith', 'Dimensional Check', 'Pass', 0, 'All measurements within tolerance'),
('QC-2025-002', 'Steel Office Desk', 'SOD-002', '2025-01-16', 'Sarah Johnson', 'Functional Test', 'Fail', 3, 'Drawer mechanism needs adjustment'),
('QC-2025-003', 'Aluminum Window Frame', 'AWF-003', '2025-01-17', 'Mike Wilson', 'Material Analysis', 'Pass', 0, 'Material composition verified'),
('QC-2025-004', 'Motor Assembly Unit', 'MAU-004', '2025-01-18', 'Emily Davis', 'Assembly Check', 'Pending', 0, 'Inspection in progress'),
('QC-2025-005', 'Circuit Board Assembly', 'CBA-005', '2025-01-19', 'Robert Brown', 'Stress Test', 'Warning', 1, 'Minor solder joint defect detected'),
('QC-2025-006', 'Hydraulic System', 'HS-006', '2025-01-20', 'Lisa Chen', 'Pressure Test', 'Pass', 0, 'All pressure tests passed'),
('QC-2025-007', 'Solar Panel Frame', 'SPF-007', '2025-01-21', 'Tom Anderson', 'Weather Resistance', 'Pass', 0, 'Weather resistance verified');


-- Populate "MANM".logistics
INSERT INTO "MANM".logistics ("shipment_id", "order_number", "carrier", "tracking_number", "origin", "destination", "departure_date", "estimated_arrival", "status", "priority") VALUES
('SH-2025-001', 'CO-2025-001', 'FedEx Express', '1234567890', 'Warehouse A', 'New York, NY', '2025-01-15', '2025-01-17', 'In Transit', 'High'),
('SH-2025-002', 'CO-2025-002', 'UPS Ground', '1Z9876543210', 'Warehouse B', 'Los Angeles, CA', '2025-01-16', '2025-01-19', 'Delivered', 'Medium'),
('SH-2025-003', 'CO-2025-003', 'DHL International', 'DHL123456789', 'Warehouse C', 'Chicago, IL', '2025-01-18', '2025-01-20', 'Preparing', 'Low'),
('SH-2025-004', 'CO-2025-004', 'USPS Priority', 'USPS987654321', 'Warehouse A', 'Houston, TX', '2025-01-20', '2025-01-22', 'Delayed', 'High'),
('SH-2025-005', 'CO-2025-005', 'FedEx Ground', 'FDX555444333', 'Warehouse D', 'Miami, FL', '2025-01-22', '2025-01-24', 'In Transit', 'Medium'),
('SH-2025-006', 'CO-2025-006', 'DHL Express', 'DHL987654321', 'Warehouse E', 'Seattle, WA', '2025-01-24', '2025-01-26', 'In Transit', 'High'),
('SH-2025-007', 'CO-2025-007', 'UPS Express', '1Z1234567890', 'Warehouse F', 'Boston, MA', '2025-01-25', '2025-01-27', 'Delivered', 'Medium');


-- Populate "MANM".procurement
INSERT INTO "MANM".procurement ("po_number", "supplier", "material_name", "item_code", "quantity", "unit_price", "total_amount", "order_date", "expected_delivery", "status", "related_order") VALUES
('PO-2025-001', 'Rubber Industries', 'Rubber Gaskets', 'INV-0003', 50, 3.25, 162.50, '2025-01-24', '2025-01-31', 'Ordered', 'CO-2025-003'),
('PO-2025-002', 'MetalCraft Industries', 'Steel Bolts M8x50', 'INV-0002', 100, 0.75, 75.00, '2025-01-30', '2025-02-03', 'Approved', 'CO-2025-006'),
('PO-2025-003', 'Titanium Tech Ltd', 'Titanium Screws', 'INV-0015', 200, 2.50, 500.00, '2025-02-01', '2025-02-13', 'Pending', 'CO-2025-007');

-- --- END OF SCRIPT ---
